force-app/main/default/objects/sfcraft_LwcApiSettings__c/sfcraft_LwcApiSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SfCraft LWC API Settings</label>
</CustomObject>

force-app/main/default/objects/sfcraft_LwcApiSettings__c/fields/ErrorHandlerImplementation__c.field-meta.xml
<CustomField>
    <fullName>ErrorHandlerImplementation__c</fullName>
    <defaultValue>&quot;sfcraft_LwcApiDefaultErrorHandler&quot;</defaultValue>
    <description
    >sfcraft_ILwcApiErrorHandler implementation to run before wrapping an error into the AuraHandledException</description>
    <inlineHelpText
    >sfcraft_ILwcApiErrorHandler implementation to run before wrapping an error into the AuraHandledException</inlineHelpText>
    <label>Error Handler Implementation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/src/framework/dependencyInjection/sfcraft_LwcApiDependencies.cls
public without sharing class sfcraft_LwcApiDependencies {
    private static sfcraft_LwcApiDependencies instance;

    public static sfcraft_LwcApiDependencies getInstance() {
        if (null == instance) {
            instance = new sfcraft_LwcApiDependencies();
        }
        return instance;
    }

    private sfcraft_LwcApiSettings__c settings;

    private sfcraft_ILwcApiErrorHandler errorHandler;

    private sfcraft_LwcApiDependencies() {
        List<sfcraft_LwcApiSettings__c> settingExistenceCheck = [
            SELECT Id
            FROM sfcraft_LwcApiSettings__c
            WHERE SetupOwnerId = :UserInfo.getOrganizationId()
        ];
        if (settingExistenceCheck.isEmpty()) {
            insert new sfcraft_LwcApiSettings__c();
        }
        this.settings = sfcraft_LwcApiSettings__c.getInstance(
            UserInfo.getUserId()
        );
    }

    public sfcraft_ILwcApiErrorHandler getErrorHandler() {
        if (null == this.errorHandler) {
            String errorHandlerName = this.settings.ErrorHandlerImplementation__c;
            this.errorHandler = (sfcraft_ILwcApiErrorHandler) Type.forName(
                    errorHandlerName
                )
                .newInstance();
        }
        return this.errorHandler;
    }
}